plugins {
    id 'java-library'
}

description = 'Runtime Registry module for runtime capacity registration and selection.'

dependencies {
    implementation 'org.postgresql:postgresql'

    testImplementation "org.testcontainers:testcontainers:${testcontainersVersion}"
    testImplementation "org.testcontainers:testcontainers-junit-jupiter:${testcontainersVersion}"
    testImplementation "org.testcontainers:testcontainers-postgresql:${testcontainersVersion}"

    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
